- name: setup instances
  ec2:
    aws_access_key: "{{ access }}"
    aws_secret_key: "{{ secret }}"
    region: "{{ region }}"
    image: "{{ ami_id }}"
    instance_type: "{{ instance_type }}"
    group: "{{ sg }}"
    key_name: "{{ key }}"
    vpc_subnet_id: "{{ subnet_id }}"
    assign_public_ip: yes
    monitoring: yes
    wait: yes
    wait_timeout: 500
    count: 2
    instance_tags:
       nagios: client
       Name: frontend
